{{- if .Values.secrets }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.application }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    project: {{ .Values.project }}
    application: {{ .Values.application }}
data:
  {{- range $key, $value := .Values.secrets}}
  {{ $key }}: {{ $value | b64enc }}
  {{ end }}

{{ end }}