#project
namespace: 
project: 

#application
application: 
image: 

#resource
replicaCount: 1
maximum:
  cpu: 200m
  memory: 100Mi
minimum:
  cpu: 100m
  memory: 50Mi

#container
container:
  environment:
    map:
      check: value
    secrets:
      - name: db-secret
        keys:
          - DB_PASSWORD
          - DB_USERNAME

#networking
service:
  ports:
    - name: cart-port
      protocol: TCP
      svcPort: 8080
      containerPort: 8080

#containerSecrets
secrets:
  DB_USER: admin
  DB_PASSWORD: secret

#configMap
config:
  mapType:
    player_initial_lives: "3"
    ui_properties_file_name: "user-interface.properties"
  fileType:
    game.properties: |
      enemy.types=aliens,monsters
      player.maximum-lives=5